// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUabEb9ZP9a2BqU1_NQ3ZhMFfJ7tm-j5I',
    appId: '1:528484579983:web:c7f380f2e5039460644efa',
    messagingSenderId: '528484579983',
    projectId: 'social-app-b33bd',
    authDomain: 'social-app-b33bd.firebaseapp.com',
    storageBucket: 'social-app-b33bd.firebasestorage.app',
    measurementId: 'G-H9VY3ZFMCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUF3Z6giMUl-3vATreh5odudyBvPAgQkM',
    appId: '1:528484579983:android:f875450d9d751cf5644efa',
    messagingSenderId: '528484579983',
    projectId: 'social-app-b33bd',
    storageBucket: 'social-app-b33bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsEfNQmf3UKKSWaCT3toBkzVbCk3VCWSk',
    appId: '1:528484579983:ios:dc47fe0808e3463d644efa',
    messagingSenderId: '528484579983',
    projectId: 'social-app-b33bd',
    storageBucket: 'social-app-b33bd.firebasestorage.app',
    iosBundleId: 'ma.omerta.mycommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsEfNQmf3UKKSWaCT3toBkzVbCk3VCWSk',
    appId: '1:528484579983:ios:dc47fe0808e3463d644efa',
    messagingSenderId: '528484579983',
    projectId: 'social-app-b33bd',
    storageBucket: 'social-app-b33bd.firebasestorage.app',
    iosBundleId: 'ma.omerta.mycommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUabEb9ZP9a2BqU1_NQ3ZhMFfJ7tm-j5I',
    appId: '1:528484579983:web:9901a1930afa9523644efa',
    messagingSenderId: '528484579983',
    projectId: 'social-app-b33bd',
    authDomain: 'social-app-b33bd.firebaseapp.com',
    storageBucket: 'social-app-b33bd.firebasestorage.app',
    measurementId: 'G-XNXBJE7F23',
  );
}
